version: '2'

services:
    php:
        container_name: ecomitize_task.php_1
        build:
            context: ./docker/php
        volumes:
            - ./application:/application
        tty: true
        working_dir: /application
        env_file: .env
